const SUPABASE_URL = 'PEGA_AQUI_TU_SUPABASE_URL';
const SUPABASE_ANON_KEY = 'PEGA_AQUI_TU_SUPABASE_ANON_KEY';
const USE_SUPABASE = !SUPABASE_URL.includes('PEGA_AQUI');
const sb = USE_SUPABASE ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const demoCourses=[{title:'Excel Básico Interactivo',level:'Básico',desc:'Celdas, fórmulas, tablas y retos guiados.',tags:['Gratis','Interactivo']},{title:'Power BI desde cero',level:'Básico',desc:'Carga de datos, modelo y dashboard visual.',tags:['Premium','Dashboard']},{title:'SQL para reportes',level:'Básico',desc:'Consultas, filtros, joins y ejercicios.',tags:['Gratis','Práctica']},{title:'IA para oficina',level:'Intermedio',desc:'Prompts para reportes, Excel y productividad.',tags:['Premium','IA']},{title:'Excel para supervisores',level:'Intermedio',desc:'Control de trabajos, avances y KPIs.',tags:['Plantillas','Operativo']},{title:'Power Query práctico',level:'Avanzado',desc:'Limpieza y transformación de datos.',tags:['Premium','Automatización']}];
const demoResources=[{title:'Plantilla Control de Trabajos',category:'Excel',access:'premium',price:19},{title:'Ejercicios SQL Básico',category:'SQL',access:'free',price:0},{title:'Dashboard Supervisión',category:'Power BI',access:'premium',price:29}];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderCards(){const c=$('#courseGrid');c.innerHTML=demoCourses.map(x=>`<article class="card"><span class="pill">${x.level}</span><h3>${x.title}</h3><p>${x.desc}</p>${x.tags.map(t=>`<span class="tag">${t}</span>`).join('')}<br><br><a class="btn ghost" href="#leccion-demo" onclick="setStep(0);setTimeout(()=>document.getElementById('leccion-demo').scrollIntoView({behavior:'smooth'}),50)">Entrar al curso</a></article>`).join('');const r=$('#resourceGrid');r.innerHTML=demoResources.map(x=>`<article class="card"><span class="pill">${x.category}</span><h3>${x.title}</h3><p>${x.access==='premium'?'Premium':'Gratis'} ${x.price?`• S/ ${x.price}`:''}</p><button class="btn secondary" onclick="requestResource('${x.title}')">Solicitar</button></article>`).join('')}
function requestResource(title){location.href=`https://wa.me/51999999999?text=Hola%2C%20quiero%20el%20recurso%3A%20${encodeURIComponent(title)}`}
let step=0;function setStep(i){step=i;$$('.lesson-step').forEach((e,k)=>e.classList.toggle('active',k===i));const s=$('#lessonStage');const screens=[`<div class="stage-card"><span class="pill">Paso 1</span><h2>Bienvenido a Excel Básico</h2><p>Aprenderás viendo, tocando y practicando. Presiona siguiente para iniciar.</p><button class="btn primary" onclick="setStep(1)">Siguiente</button></div>`,`<div class="stage-card"><span class="pill">Paso 2</span><h2>Conoce la hoja de cálculo</h2><p>Las columnas son letras, las filas son números y cada cuadro es una celda.</p><div class="excel-sim"><div></div><div class="head">A</div><div class="head">B</div><div class="head">C</div><div class="head">D</div>${Array.from({length:12}).map((_,idx)=>idx%4===0?`<div class="head">${idx/4+1}</div><div class="cell"></div>`:`<div class="cell"></div>`).join('')}</div><button class="btn primary" onclick="setStep(2)">Practicar</button></div>`,`<div class="stage-card"><span class="pill">Paso 3</span><h2>Toca la celda B2</h2><p id="clickMsg">Busca la celda marcada por columna B y fila 2.</p><div class="excel-sim" id="practiceGrid"><div></div><div class="head">A</div><div class="head">B</div><div class="head">C</div><div class="head">D</div>${[1,2,3].map(row=>`<div class="head">${row}</div>${['A','B','C','D'].map(col=>`<button class="cell ${col==='B'&&row===2?'target':''}" onclick="cellClick('${col}${row}')">${col}${row}</button>`).join('')}`).join('')}</div><button class="btn ghost" onclick="setStep(3)">Saltar</button></div>`,`<div class="stage-card"><span class="pill">Paso 4</span><h2>Escribe una fórmula</h2><p>Escribe exactamente: =SUMA(A1:A10)</p><input class="formula-input" id="formulaInput" placeholder="Escribe aquí"/><br><br><button class="btn primary" onclick="checkFormula()">Validar</button><p id="formulaMsg"></p></div>`,`<div class="stage-card"><span class="pill">Paso 5</span><h2>Mini quiz</h2><p>¿Qué símbolo inicia una fórmula en Excel?</p><button class="btn ghost" onclick="quiz(false)">+</button> <button class="btn ghost" onclick="quiz(true)">=</button> <button class="btn ghost" onclick="quiz(false)">#</button><p id="quizMsg"></p></div>`];s.innerHTML=screens[i]}
window.cellClick=(v)=>{const m=$('#clickMsg'); if(v==='B2'){m.innerHTML='✅ Excelente. Ganaste +10 XP.';setTimeout(()=>setStep(3),900)}else m.innerHTML='❌ Casi. Intenta tocar B2.'}
window.checkFormula=()=>{const ok=$('#formulaInput').value.trim().toUpperCase()==='=SUMA(A1:A10)';$('#formulaMsg').innerHTML=ok?'✅ Correcto. +20 XP.':'❌ Revisa los dos puntos del rango.';if(ok)setTimeout(()=>setStep(4),900)}
window.quiz=(ok)=>{$('#quizMsg').innerHTML=ok?'🏆 Correcto. Lección completada.':'❌ Incorrecto. Las fórmulas empiezan con ='}; window.setStep=setStep;
async function loadAdmin(){ $('#admin').classList.remove('hidden'); $('#kpiUsers').textContent='128';$('#kpiSubs').textContent='24';$('#kpiSales').textContent='S/ 1,240';$('#kpiDownloads').textContent='376';renderAdminResources(demoResources)}
function renderAdminResources(list){$('#adminResources').innerHTML=list.map(x=>`<div class="table-row"><b>${x.title}</b><span>${x.category}</span><span>${x.access}</span></div>`).join('')}
async function isAdmin(){ if(!USE_SUPABASE)return true; const {data:{user}}=await sb.auth.getUser(); if(!user)return false; const {data}=await sb.from('profiles').select('role').eq('id',user.id).single(); return data?.role==='admin'}
async function handleAuth(e){e.preventDefault();const mode=e.submitter.value;const email=e.target.email.value;const password=e.target.password.value;$('#authMsg').textContent='Procesando...'; if(!USE_SUPABASE){$('#authMsg').textContent='Modo local: configura Supabase para login real. Se abre admin.';$('#loginModal').classList.add('hidden');loadAdmin();location.hash='admin';return} const res= mode==='signup'? await sb.auth.signUp({email,password}) : await sb.auth.signInWithPassword({email,password}); if(res.error){$('#authMsg').textContent=res.error.message;return} $('#loginModal').classList.add('hidden'); if(await isAdmin()) loadAdmin(); else $('#authMsg').textContent='Ingresaste como alumno.'}
async function saveResource(e){e.preventDefault(); if(!USE_SUPABASE){alert('Configura Supabase para guardar archivos reales.');return} const f=e.target.file.files[0]; let publicUrl=''; if(f){const path=`${Date.now()}_${f.name}`; const up=await sb.storage.from('recursos').upload(path,f); if(up.error){alert(up.error.message);return} publicUrl=sb.storage.from('recursos').getPublicUrl(path).data.publicUrl} const row={title:e.target.title.value,category:e.target.category.value,access:e.target.access.value,price:Number(e.target.price.value||0),description:e.target.description.value,file_url:publicUrl}; const ins=await sb.from('resources').insert(row); if(ins.error) alert(ins.error.message); else alert('Recurso guardado');}
async function saveLesson(e){e.preventDefault(); if(!USE_SUPABASE){alert('Configura Supabase para guardar lecciones reales.');return} alert('Base lista. En la siguiente mejora guardaremos bloques múltiples con orden.');}
function init(){renderCards();setStep(0);$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$('#openLoginBtn').onclick=()=>$('#loginModal').classList.remove('hidden');$('#closeLogin').onclick=()=>$('#loginModal').classList.add('hidden');$('#adminShortcut').onclick=()=>$('#loginModal').classList.remove('hidden');$('#authForm').onsubmit=handleAuth;$('#resourceForm').onsubmit=saveResource;$('#lessonForm').onsubmit=saveLesson;$('#logoutBtn').onclick=async()=>{if(USE_SUPABASE)await sb.auth.signOut();$('#admin').classList.add('hidden')};$$('.lesson-step').forEach((e,i)=>e.onclick=()=>setStep(i)); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
