const $ = s => document.querySelector(s);
const app = $('#app');
const state = {view:'home', filter:'Todos', current:null, step:0, xp:+localStorage.ch_xp||0, done: JSON.parse(localStorage.ch_done||'[]')};
const steps = ['intro','video','practice','formula','quiz','finish'];
function save(){localStorage.ch_xp=state.xp;localStorage.ch_done=JSON.stringify(state.done)}
function toast(t){const el=$('#toast');el.textContent=t;el.style.display='block';setTimeout(()=>el.style.display='none',2200)}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-PE';u.rate=.95;speechSynthesis.speak(u)}catch(e){toast(t)}}
function nav(v){state.view=v; state.step=0; render(); scrollTo(0,0)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>nav(b.dataset.view));
function home(){app.innerHTML=`<section class="hero"><div class="panel"><span class="pill">Versión oficial • Motor interactivo v4</span><h1>Aprende Excel practicando, no solo mirando.</h1><p class="lead">Ruta completa de 300 lecciones desde fundamentos hasta experto, con tutor de voz, simulador, retos, quiz, XP y constructor inicial.</p><button class="primary" onclick="nav('academy')">Entrar a la academia</button></div><div class="panel stats"><div class="stat"><b>300</b><span>Lecciones Excel</span></div><div class="stat"><b>${state.done.length}</b><span>Completadas</span></div><div class="stat"><b>${state.xp}</b><span>XP ganados</span></div><div class="stat"><b>5</b><span>Niveles</span></div></div></section><section class="grid" style="margin-top:16px"><div class="card"><h3>🎙 Tutor IA</h3><p class="meta">Guía por voz, pistas y corrección.</p></div><div class="card"><h3>🧪 Simulador Excel</h3><p class="meta">Práctica directa en la web.</p></div><div class="card"><h3>🛠 Constructor</h3><p class="meta">Crea lecciones por bloques.</p></div></section>`}
function academy(){let levels=['Todos',...new Set(EXCEL_LESSONS.map(x=>x.level))];let filtered=state.filter=='Todos'?EXCEL_LESSONS:EXCEL_LESSONS.filter(x=>x.level==state.filter);app.innerHTML=`<div class="panel"><span class="pill">Academia Excel completa</span><h2>Ruta de básico a experto</h2><div class="levels">${levels.map(l=>`<button class="level ${state.filter==l?'primary':''}" onclick="state.filter='${l}';render()">${l}</button>`).join('')}</div><div class="progressbar"><span style="width:${Math.round(state.done.length/EXCEL_LESSONS.length*100)}%"></span></div><p class="meta">Progreso total: ${state.done.length}/${EXCEL_LESSONS.length} lecciones</p></div><div class="grid" style="margin-top:14px">${filtered.slice(0,120).map(l=>card(l)).join('')}</div><p class="meta">Se muestran 120 tarjetas por rendimiento móvil. Filtra por nivel para ver el resto.</p>`}
function card(l){let d=state.done.includes(l.id);return `<article class="card lesson-card"><span class="pill">${l.level}</span><h3>${l.id} • ${l.title}</h3><p class="meta">${l.duration} • ${l.xp} XP</p><p>${l.objective}</p><button class="${d?'ok':'primary'}" onclick="openLesson('${l.id}')">${d?'Repetir':'Entrar'}</button></article>`}
function openLesson(id){state.current=EXCEL_LESSONS.find(x=>x.id==id);state.step=0;state.view='lesson';render();speak(`Bienvenido. ${state.current.scenario}. Presiona siguiente para empezar.`)}
function lesson(){let l=state.current||EXCEL_LESSONS[0];let s=steps[state.step];app.innerHTML=`<section class="lesson-layout"><aside class="panel sidebar"><h3>Ruta Excel</h3><div class="lesson-list">${EXCEL_LESSONS.slice(0,60).map(x=>`<div class="lesson-item ${x.id==l.id?'active':''}" onclick="openLesson('${x.id}')"><b>${x.id}</b><br><span class="meta">${x.title}</span></div>`).join('')}</div></aside><section class="panel stage"><div class="timeline">${steps.map((x,i)=>`<span class="dot ${i<=state.step?'on':''}"></span>`).join('')}</div><div class="tutor"><div class="avatar">🤖</div><div><b>Profesor CampusHugo</b><p id="tutorText">${tutorText(l,s)}</p><button onclick="speak(document.getElementById('tutorText').innerText)">🔊 Escuchar guía</button></div></div>${renderStep(l,s)}<div style="display:flex;gap:8px;margin-top:14px;flex-wrap:wrap"><button onclick="prevStep()">Anterior</button><button class="primary" onclick="nextStep()">Siguiente</button><button onclick="nav('academy')">Volver</button></div></section></section>`}
function tutorText(l,s){return {intro:`Hoy trabajarás: ${l.title}. ${l.scenario}`,video:`Observa la explicación visual. La idea es entender primero y practicar después.`,practice:`Toca la celda B5. En celular debes tocar justo el cuadro marcado en amarillo.`,formula:`Ahora escribe la fórmula ${l.practice.formula}. Respeta el signo igual, paréntesis y dos puntos.`,quiz:`Responde la pregunta para validar que entendiste la lección.`,finish:`Excelente. Completa la lección para ganar XP y desbloquear más práctica.`}[s]}
function renderStep(l,s){if(s=='intro')return `<h2>${l.title}</h2><p class="lead">${l.objective}</p><div class="card"><h3>🎯 Caso real</h3><p>${l.scenario}</p></div>`;if(s=='video')return `<div class="card"><h3>🎬 Video animado simulado</h3><p>En una versión con contenido final aquí irá un video corto o animación. Ahora el motor reproduce la secuencia guiada.</p><div style="height:160px;border-radius:18px;background:linear-gradient(135deg,#1b3e68,#7c5cff);display:grid;place-items:center;font-size:54px">▶️</div></div>`;if(s=='practice')return excelGrid();if(s=='formula')return `${excelGrid()}<input class="formulaBox" id="formula" placeholder="Escribe aquí: ${l.practice.formula}"/><button class="ok" onclick="checkFormula()">Revisar fórmula</button>`;if(s=='quiz')return `<div class="quiz"><h3>${l.quiz.q}</h3>${l.quiz.options.map((o,i)=>`<button onclick="checkQuiz(${i})">${o}</button>`).join('')}</div>`;return `<div class="card"><h2>🏆 Lección completada</h2><p>Ganaste ${l.xp} XP.</p><button class="ok" onclick="completeLesson()">Guardar progreso</button></div>`}
function excelGrid(){let cells=['','A','B','C','D','E'];let html='<div class="excel"><div class="excelbar">Excel simulado - práctica guiada</div><div class="sheet">';cells.forEach(c=>html+=`<div class="cell head">${c}</div>`);for(let r=1;r<=6;r++){html+=`<div class="cell head">${r}</div>`;for(let c of ['A','B','C','D','E']){let id=c+r;html+=`<div class="cell ${id=='B5'?'target':''}" onclick="cellClick('${id}',this)">${id=='A1'?10:id=='A2'?20:id=='A3'?30:''}</div>`}}return html+'</div></div>'}
function cellClick(id,el){if(id=='B5'){el.classList.add('good');toast('Correcto: seleccionaste B5');speak('Excelente, seleccionaste la celda B5. Ahora continúa.')}else{speak('Aún no. Busca la celda B5: columna B, fila 5.')}}
function checkFormula(){let l=state.current;let val=$('#formula').value.trim().toUpperCase().replaceAll(' ',''); if(val==l.practice.formula){toast('Fórmula correcta');speak('Perfecto. La fórmula está bien escrita.'); state.step=4; render()} else speak('Revisa la fórmula. Debe iniciar con igual y usar el rango correcto.')}
function checkQuiz(i){let l=state.current;if(i==l.quiz.answer){toast('Respuesta correcta');speak('Muy bien. Ya puedes finalizar la lección.');state.step=5;render()}else speak('No es la mejor respuesta. La clave es practicar resolviendo casos reales.')}
function completeLesson(){let l=state.current;if(!state.done.includes(l.id)){state.done.push(l.id);state.xp+=l.xp;save()}toast('Progreso guardado');nav('academy')}
function nextStep(){if(state.step<steps.length-1)state.step++;render()}function prevStep(){if(state.step>0)state.step--;render()}
function admin(){app.innerHTML=`<div class="panel"><span class="pill">Constructor visual inicial</span><h2>Crear lección interactiva</h2><p class="lead">Este módulo es la base del panel admin. En la siguiente fase se conectará a Supabase para guardar cursos reales.</p><div class="grid2"><div><label>Título</label><input id="newTitle" placeholder="Ej: BUSCARX paso a paso"><label>Nivel</label><select id="newLevel"><option>Básico</option><option>Intermedio</option><option>Avanzado</option></select><label>Objetivo</label><textarea id="newObj" placeholder="Qué aprenderá el alumno"></textarea><button class="primary" onclick="addLocalLesson()">Crear en borrador</button></div><div><h3>Bloques disponibles</h3>${['🎥 Video','🖼 Imagen','🎙 Audio','📊 Excel simulado','💻 SQL','❓ Quiz','🏆 Proyecto','📁 Descarga'].map(x=>`<div class="builder-block">${x}</div>`).join('')}</div></div></div><div id="drafts" class="grid" style="margin-top:14px"></div>`;renderDrafts()}
function addLocalLesson(){let d=JSON.parse(localStorage.ch_drafts||'[]');d.push({title:$('#newTitle').value,level:$('#newLevel').value,obj:$('#newObj').value});localStorage.ch_drafts=JSON.stringify(d);renderDrafts();toast('Borrador creado')}
function renderDrafts(){let el=$('#drafts');if(!el)return;let d=JSON.parse(localStorage.ch_drafts||'[]');el.innerHTML=d.map(x=>`<div class="card"><span class="pill">${x.level}</span><h3>${x.title}</h3><p>${x.obj}</p></div>`).join('')}
function progress(){app.innerHTML=`<div class="panel"><h2>Mi progreso</h2><div class="stats"><div class="stat"><b>${state.done.length}</b><span>Lecciones completadas</span></div><div class="stat"><b>${state.xp}</b><span>XP total</span></div><div class="stat"><b>${Math.round(state.done.length/EXCEL_LESSONS.length*100)}%</b><span>Ruta Excel</span></div><div class="stat"><b>${Math.floor(state.xp/500)+1}</b><span>Nivel actual</span></div></div></div>`}
function render(){({home,academy,lesson,admin,progress}[state.view]||home)()}
render();
